In [21]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler 
from sklearn.decomposition import PCA

df = pd.read_csv("../data/예제/USArrests_rownames.csv", index_col=0)
display(df.head()) 

x = StandardScaler().fit_transform(df)

pca = PCA(n_components=4)

pca_arr = pca.fit_transform(x)

result = {
    "분산기여율": pca.explained_variance_ratio_, 
    "누적기여률": pca.explained_variance_ratio_.cumsum(), 
}

result = pd.DataFrame(result, index=["PCA1", "PCA2", "PCA3", "PCA4"]).T


pca = PCA(n_components=2)
pca_arr = pca.fit_transform(x)
df_pca = pd.DataFrame(pca_arr, columns=["PCA1", "PCA2"])
df_pca

            Murder  Assault  UrbanPop  Rape
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

        PCA1      PCA2
0   0.985566 -1.133392
1   1.950138 -1.073213
2   1.763164  0.745957
3  -0.141420 -1.119797
4   2.523980  1.542934
5   1.514563  0.987555
6  -1.358647  1.088928
7   0.047709  0.325359
8   3.013042 -0.039229
9   1.639283 -1.278942
10 -0.912657  1.570460
11 -1.639800 -0.210973
12  1.378911  0.681841
13 -0.505461  0.151563
14 -2.253646  0.104054
15 -0.796881  0.270165
16 -0.750859 -0.958440
17  1.564818 -0.871055
18 -2.396829 -0.376392
19  1.763369 -0.427655
20 -0.486166  1.474496
21  2.108441  0.155397
22 -1.692682  0.632261
23  0.996494 -2.393796
24  0.696787  0.263355
25 -1.185452 -0.536874
26 -1.265637  0.193954
27  2.874395  0.775600
28 -2.383915  0.018082
29  0.181566  1.449506
30  1.980024 -0.142849
31  1.682577  0.823184
32  1.123379 -2.228003
33 -2.992226 -0.599119
34 -0.225965  0.742238
35 -0.311783  0.287854
36  0.059122  0.541411
37 -0.888416  0.571100
38 -0.863772  1.491978
39  1.320724 -1.933405
40 -1.987775 -0.823343
41  0.999742 -0.860251
42  1.355138  0.412481
43 -0.550565  1.471505
44 -2.801412 -1.402288
45 -0.096335 -0.199735
46 -0.216903  0.970124
47 -2.108585 -1.424847
48 -2.079714  0.611269
49 -0.629427 -0.321013